import React from 'react';
import { BlogDetail } from '../features/blog/BlogDetail';
import { type BlogArticle, type BlogAuthor } from '../features/blog';

export const BlogDetailTest: React.FC = () => {
  // Mock author
  const mockAuthor: BlogAuthor = {
    id: '1',
    name: 'Admin TMC',
    avatar: '/api/placeholder/100/100',
    role: 'Content Manager',
  };


  // Mock article with HTML content from TiptapEditor
  const mockArticle: BlogArticle = {
    id: '1',
    pk: 1,
    title: 'Test Blog Post - HTML to Markdown Conversion',
    excerpt: 'Testing the MarkdownRenderer component with HTML content from TiptapEditor',
    content: `
      <h1>Advanced HTML to Markdown Testing</h1>
      <p>This is a comprehensive test of the <strong>MarkdownRenderer</strong> component with <em>various HTML elements</em> that might be generated by TiptapEditor.</p>
      
      <h2>Text Formatting</h2>
      <p>Here we test <strong>bold text</strong>, <em>italic text</em>, and <code>inline code</code>. We can also combine them like <strong><em>bold italic</em></strong> text.</p>
      
      <h3>Lists</h3>
      <p>Unordered list:</p>
      <ul>
        <li>First item with <strong>bold</strong> text</li>
        <li>Second item with <em>italic</em> text</li>
        <li>Third item with <code>inline code</code></li>
        <li>Nested list:
          <ul>
            <li>Nested item 1</li>
            <li>Nested item 2</li>
          </ul>
        </li>
      </ul>
      
      <p>Ordered list:</p>
      <ol>
        <li>Step one</li>
        <li>Step two</li>
        <li>Step three</li>
      </ol>
      
      <h3>Code Blocks</h3>
      <p>Here's a JavaScript code example:</p>
      <pre><code>const MarkdownRenderer = ({ content }) => {
  const isHtml = /<[^>]*>/g.test(content);
  
  if (isHtml) {
    return <ReactMarkdown>{htmlToMarkdown(content)}</ReactMarkdown>;
  }
  
  return <ReactMarkdown>{content}</ReactMarkdown>;
};</code></pre>
      
      <h3>Blockquotes</h3>
      <blockquote>
        <p>This is a blockquote that should be properly converted from HTML to Markdown. It can contain <strong>formatted text</strong> and even <a href="https://example.com">links</a>.</p>
      </blockquote>
      
      <h3>Links and Images</h3>
      <p>Here's a <a href="https://tmclub.id">link to TMC website</a> and another <a href="https://github.com/remarkjs/react-markdown">link to react-markdown</a>.</p>
      
      <h3>Tables</h3>
      <table>
        <thead>
          <tr>
            <th>Feature</th>
            <th>Status</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>HTML to Markdown</td>
            <td>✅ Working</td>
            <td>Converts HTML elements to Markdown</td>
          </tr>
          <tr>
            <td>Code Highlighting</td>
            <td>✅ Working</td>
            <td>Syntax highlighting for code blocks</td>
          </tr>
          <tr>
            <td>Responsive Design</td>
            <td>✅ Working</td>
            <td>Mobile-friendly layout</td>
          </tr>
        </tbody>
      </table>
      
      <h3>Mixed Content</h3>
      <p>This paragraph contains multiple elements: <strong>bold</strong>, <em>italic</em>, <code>code</code>, and a <a href="https://example.com">link</a>. It should all render correctly.</p>
      
      <hr />
      
      <h2>Conclusion</h2>
      <p>This test verifies that the <code>MarkdownRenderer</code> component can handle complex HTML content from TiptapEditor and convert it properly to Markdown for consistent rendering.</p>
    `,
    slug: 'test-blog-post-html-markdown',
    featuredImage: '/api/placeholder/800/400',
    author: mockAuthor,
    tags: ['Testing', 'Markdown', 'HTML', 'TiptapEditor', 'React'],
    status: 'published',
    publishedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    readTime: 5,
    views: 123,
    likes: 15,
    comments: 3,
    featured: true,
  };

  const handleBack = () => {
    window.history.back();
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto p-6">
        <div className="mb-6 text-center">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Blog Detail Test</h1>
          <p className="text-gray-600">Testing MarkdownRenderer with HTML content from TiptapEditor</p>
        </div>
        
        <BlogDetail article={mockArticle} onBack={handleBack} />
      </div>
    </div>
  );
};