[build]
  # Build command using Bun
  command = "bun install && bun run build"
  
  # Directory to publish (output directory)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Bun version
  BUN_VERSION = "1.2.21"
  
  # Production environment variables
  NODE_ENV = "production"
  # Add your environment variables here
  # VITE_API_URL = "https://your-api-url.com"
  # VITE_APP_NAME = "TMC Frontend"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy rules (if needed for development)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.com/:splat"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Prerender settings (optional)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Functions directory (if you plan to use Netlify Functions)
[functions]
  directory = "netlify/functions"

# Dev settings
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"